version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80" # A porta 5000 do host acessa a 80 do container (NGINX)
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Descomente se quiser logs mais limpos e evitar erros de cache antigo
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
