services:
  frontend:
    container_name: solarshare-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # Exemplo para limitar memória do node (opcional)
      # - NODE_OPTIONS=--max-old-space-size=4096
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s  # aguarda 10s antes de começar as checagens
    logging:
      driver: json-file
      options:
        max-size: "10m"   # máximo de 10MB por arquivo de log
        max-file: "3"     # mantém até 3 arquivos rotacionados
