version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "5000:80"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
    restart: unless-stopped